// Dataset -> seed.sql text. Byte-deterministic: chunked multi-row INSERTs of at
// most 50 rows, fixed column and row order, LF line endings.
import { STAGES } from "../stages.ts";
import type { Dataset } from "./generate.ts";

export const MAX_ROWS_PER_INSERT = 50;

type Sqlish = string | number | boolean | null;

function lit(v: Sqlish): string {
  if (v === null) return "NULL";
  if (typeof v === "boolean") return v ? "1" : "0";
  if (typeof v === "number") return String(v);
  return `'${v.replace(/'/g, "''")}'`;
}

function inserts(table: string, columns: readonly string[], rows: readonly Sqlish[][]): string {
  const out: string[] = [];
  for (let i = 0; i < rows.length; i += MAX_ROWS_PER_INSERT) {
    const chunk = rows.slice(i, i + MAX_ROWS_PER_INSERT);
    out.push(
      `INSERT INTO ${table} (${columns.join(", ")}) VALUES\n` +
        chunk.map((r) => `  (${r.map(lit).join(", ")})`).join(",\n") +
        ";",
    );
  }
  return out.join("\n");
}

export function datasetToSql(d: Dataset): string {
  const header = [
    "-- OnboardFlow synthetic seed. Generated by scripts/seed.ts; do not edit by hand.",
    `-- seed=${d.seed} anchor=${d.anchor} version=${d.version}`,
    "-- All people are synthetic and use the reserved .test TLD.",
  ].join("\n");

  const staff = inserts(
    "staff",
    ["id", "email", "display_name", "kind", "department", "org_unit"],
    d.staff.map((s) => [s.id, s.email, s.displayName, s.kind, s.department, s.orgUnit]),
  );
  const employees = inserts(
    "employees",
    [
      "id",
      "email",
      "first_name",
      "last_name",
      "job_title",
      "org_unit",
      "employment_type",
      "work_mode",
      "site",
      "start_date",
      "manager_id",
      "equipment_profile",
      "license_bundle",
      "needs_privileged_access",
      "cost_center",
      "photo_on_file",
      "seed_version",
      "updated_at",
    ],
    d.employees.map((e) => [
      e.id,
      e.email,
      e.firstName,
      e.lastName,
      e.jobTitle,
      e.orgUnit,
      e.employmentType,
      e.workMode,
      e.site,
      e.startDate,
      e.managerId,
      e.equipmentProfile,
      e.licenseBundle,
      e.needsPrivilegedAccess,
      e.costCenter,
      e.photoOnFile,
      d.version,
      d.seededAt,
    ]),
  );
  const users = inserts(
    "app_users",
    ["email", "role", "employee_id", "staff_id", "active"],
    d.users.map((u) => [u.email, u.role, u.employeeId, u.staffId, 1]),
  );
  const cases = inserts(
    "cases",
    ["employee_id", "status", "updated_at"],
    d.employees.map((e) => [e.id, "not_started", d.seededAt]),
  );
  const caseStages = inserts(
    "case_stages",
    ["employee_id", "stage_id", "status", "round", "updated_at"],
    d.employees.flatMap((e) => STAGES.map((s) => [e.id, s.id, "pending", 1, d.seededAt] as Sqlish[])),
  );

  return [header, staff, employees, users, cases, caseStages].join("\n") + "\n";
}
