// Where verification keys come from. Production: the Access team's remote JWKS
// (cached per isolate by jose). Dev and test: a local JWKS generated by
// `npm run dev:keys`, the vitest config, or the eval harness. Only the key
// source differs; verification is the same function (ADR 0003).
import { createLocalJWKSet, createRemoteJWKSet, type JSONWebKeySet, type JWTVerifyGetKey } from "jose";
import type { AppConfig } from "../config.ts";

export type KeySource = { kind: "remote" | "local"; getKey: JWTVerifyGetKey; issuer: string; audience: string };

const remoteSets = new Map<string, JWTVerifyGetKey>();
const localSets = new WeakMap<JSONWebKeySet, JWTVerifyGetKey>();

export function accessCertsUrl(teamDomain: string): string {
  return `${teamDomain}/cdn-cgi/access/certs`;
}

export function keySourceFor(config: AppConfig): KeySource {
  if (config.authMode === "access") {
    const a = config.access;
    if (!a) throw new Error("access configuration missing");
    let set = remoteSets.get(a.teamDomain);
    if (!set) {
      set = createRemoteJWKSet(new URL(accessCertsUrl(a.teamDomain)));
      remoteSets.set(a.teamDomain, set);
    }
    return { kind: "remote", getKey: set, issuer: a.teamDomain, audience: a.audience };
  }
  const d = config.dev;
  if (!d) throw new Error("dev configuration missing");
  let set = localSets.get(d.jwks);
  if (!set) {
    set = createLocalJWKSet(d.jwks);
    localSets.set(d.jwks, set);
  }
  return { kind: "local", getKey: set, issuer: d.issuer, audience: d.audience };
}
